language:
- objective-c
env:
  global: LATEST_TAG=1
  matrix:
  - VERSION=2.7.8 NUMPY_VERSION=1.6.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION
- pip install cython wheel
- if [ -n "$LATEST_TAG" ]; then checkout_closest_tag pandas; fi
- cd pandas
- python setup.py bdist_wheel
- rename_wheels dist
- pip install dist/*.whl
- cd ..
script:
- pip install nose
- mkdir tmp_for_test
- cd tmp_for_test
- nosetests pandas
- cd ..
before_deploy: cd pandas/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: O71PTUeRr6ER/EM4YpKuirOb9cJYjODDqNbYaeus1/sExFhhgbFJGgh/OiiEvzwec9HycuQzMRleRpyiYuRxzc4BAT8OekzvwwVuKmV4hcK+KVau67XuQatVoVDWsAZ6Pl1MvxSOIBwda1/S5RqBTCmz4D7W6WYMxl0MQKQVF8s=
  region: ORD
  container: wheels
  skip_cleanup: true
