language:
- objective-c
env:
  global:
  - BUILD_COMMIT=v0.16.2
  - REPO_DIR=pandas
  - NIPY_WHEEL_URL=https://nipy.bic.berkeley.edu/scipy_installers
  matrix:
  - VERSION=2.7.10 NUMPY_VERSION=1.7.1
  - VERSION=3.2.5 NUMPY_VERSION=1.7.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1
  - VERSION=3.5.0 NUMPY_VERSION=1.7.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEEL_URL numpy==$NUMPY_VERSION
- pip install delocate # for renaming wheels
# Update to latest wheel package for Python 3.5
- pip install -U wheel
- pip install cython
- if [ -n "$BUILD_COMMIT" ]; then
      checkout_commit $REPO_DIR $BUILD_COMMIT;
  fi
- cd $REPO_DIR
- export CC=clang
- export CXX=clang++
- python setup.py bdist_wheel
- delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
- pip install dist/*.whl
- cd ..
script:
- pip install nose
# When pickling, numpy 1.7.1 read_array_header fails in Python 3.4
- if [ -n "$(pyver_ge $VERSION 3.4.0)" ]; then
  pip install -U -f $NIPY_WHEEL_URL numpy;
  fi
- mkdir tmp_for_test
- cd tmp_for_test
- nosetests pandas -A "not slow and not disabled" -e "test_data"
- cd ..
before_deploy:
- cd $REPO_DIR/dist
# Fix for https://github.com/travis-ci/travis-ci/issues/4635
- rvm 1.9.3 do gem install net-ssh -v 2.9.2
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "JgeIjKHFaHmDLK+OIPn5hn9N66ZCSee85pm2YtpHy9+KtPzKcURR+MGswcnh2s6KBek3yyYVFuP/KVmR48O9h/GnyNjgf0aPRfTTl/IG9Gpy4k+u9jrGH60tjHgla9npHwsKd9KqACVOdx4GDbjkzszVh0I7K9MTKFyiVgqEsio="
  region: ORD
  container: wheels
  skip_cleanup: true
