language:
- objective-c
env:
  global:
  - BUILD_COMMIT=latest-tag
  - REPO_DIR=pandas
  - NOSE_ARGS="not slow and not network and not disabled"
  matrix:
  - VERSION=2.7.10 NUMPY_VERSION=1.7.1 NUMPY_TEST_VERSION=1.7.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1 NUMPY_TEST_VERSION=1.8.1
  - VERSION=3.5.0 NUMPY_VERSION=1.7.1 NUMPY_TEST_VERSION=1.9.3 NOSE_ARGS="not slow and not network and not disabled"
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION
- pip install delocate # for renaming wheels
# Update to latest wheel package for Python 3.5
- pip install -U wheel
- pip install cython
- if [ -n "$BUILD_COMMIT" ]; then
      checkout_commit $REPO_DIR $BUILD_COMMIT;
  fi
- cd $REPO_DIR
# Need clang to reduce number of warnings for Python 3.5
- export CC=clang
- export CXX=clang++
# remove any old pandas
- python setup.py bdist_wheel
- delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
- pip install dist/*.whl
- cd ..
script:
- pip install nose
# May need to upgrade numpy to run tests successfully
- pip install numpy==$NUMPY_TEST_VERSION
- mkdir tmp_for_test
- cd tmp_for_test
# Show pandas versions before tests
- python -c 'import pandas; pandas.show_versions()'
# skip tests
#- nosetests pandas/tests/series -A "$NOSE_ARGS"
- cd ..
before_deploy:
- cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "JgeIjKHFaHmDLK+OIPn5hn9N66ZCSee85pm2YtpHy9+KtPzKcURR+MGswcnh2s6KBek3yyYVFuP/KVmR48O9h/GnyNjgf0aPRfTTl/IG9Gpy4k+u9jrGH60tjHgla9npHwsKd9KqACVOdx4GDbjkzszVh0I7K9MTKFyiVgqEsio="
  region: ORD
  container: wheels
  skip_cleanup: true
